### PR TITLE
hourly flashX fix

### PR DESCRIPTION
**Pull request by Viper2k4**

### CODE REVIEW

**Comment by tknorris** [comment]
So, what's the deal here? Are they breaking the resolver constantly or is this just defects in code?

**Comment by Viper2k4** [comment]
The breaking the resolver constantly . Right 1 hour after my new fix. The funny think is the dont change annythin until i provide a fix. Seems like they are reading here :)

**Comment by tknorris** [comment]
I contacted them via their Contact Us Page. Hopefully they'll be interested in doing a /pair solution.

**Comment by Viper2k4** [comment]
Should i fix until the unswer or should i keep the feet resting?

**Comment by tknorris** [comment]
Sure, go ahead. If they don't answer then it's their own fault.

**Pull request merged**
