### PR TITLE
added indavideo, watchonline, toltsd-fel/fixed youwatch, novamov

### PR DESCRIPTION
**Pull request by alifrezser**
Added new resolvers:
-indavideo
-watchonlie
-toltsd-fel

Fixed resolvers: 
-youwatch

Updated resolvers: 
-novamov
-rapidvideo
-flashx

### CODE REVIEW

**Comment by tknorris** [comment]
Thanks for the PR. one small request. Can you update the indvideo code to fail more gracefully when the regexes fail to match? As written, the user will get a notification along of the lines of "NoneType has no attribute group" if thye fail right now.

**Comment by alifrezser** [comment]
Hello!
I ve updated the indavideo code. Could you please check it?
Thank You

**Comment by tknorris** [comment]
indavideo looks great now, but you need to rebase because you didn't pick up my latest thevideo changes I made so the PR has merge conflicts now. Also, I already did a different fix on thevideo so you might want to revert your changes.

**Comment by tknorris** [comment]
You aren't going to be able to do it the way you are trying. You need ot use the git rebase function. You are going to create more/new conflicts trying to match my commits. It might be best to just revert all your thevideo changes. I can adapt my own for their new changes easily.

**Comment by tknorris** [comment]
Thanks!

**Comment by alifrezser** [comment]
Hopefully reverted all the changes now.

**Pull request merged**
