### PR TITLE
Some fixes + new site

### PR DESCRIPTION
**Pull request by seberoth**
Just saw that you also have fixed flashx, but your fix isn't working for me. I needed to add a call to 'http://www.flashx.tv/coding.js?cd=' to make it working again.

### CODE REVIEW

**Comment by tknorris** [comment]
Thanks for the PR!.

**Comment by elhady81** [comment]
Well done

**Comment by elhady81** [comment]
We need ol fix

**Comment by tknorris** [comment]
OL is working fine.

**Comment by elhady81** [comment]
Thank u for ur usual support but it really doesn't work could u try again
and send me latest files, and many thanks again for ur support

**Comment by tknorris** [comment]
OpenLoad is working fine. If it's not working for you then post a log.

**Comment by elhady81** [comment]
Thank u very much for ur fast response here is log file

**Comment by elhady81** [comment]
Any update my friend

**Comment by tknorris** [comment]
You didn't give me a log file...

**Comment by elhady81** [comment]
I already sent u it. Anyway i send u it again

**Comment by tknorris** [comment]
How did you send it to me?

**Comment by elhady81** [comment]
U receive it now?

**Comment by elhady81** [comment]
By mail

**Comment by tknorris** [comment]
You don't have my email address..how would you send it to me?

**Comment by elhady81** [comment]
In this mail

**Comment by elhady81** [comment]
Could u send me ur mail to seend u the file?

**Comment by tknorris** [comment]
> Could u send me ur mail to seend u the file?

Lol, no. If you want me to look at it, post a link to it here.

**Comment by elhady81** [comment]
Ok my friend here is the link

http://www2.zippyshare.com/v/P4DmYko5/file.html

**Comment by elhady81** [comment]
U find it

**Comment by tknorris** [comment]
I don't know what you are using, but that doesn't look like a Kodi log and that's not the latest version of urlresolver because ol_gmu isn't used anymore.

**Comment by elhady81** [comment]
I'm using tsmedia it's an application for enigma the same as kodi . could
you send me latest version for kodi.

**Comment by tknorris** [comment]
The latest version is in this github repo...

**Comment by tknorris** [comment]
Note, if you are re-using this code in some other box/application then it's up to you to figure out how to adapt this code to use. I can't help you with that.

**Comment by elhady81** [comment]
Thnks for help

**Pull request merged**
