### PR TITLE
2 Fixes 3 New Resolvers

### PR DESCRIPTION
**Pull request by Gujal00**
Fixes to
VideoRaj, TunePK
New Resolvers
GoFlicker, SpeedWatch and TVLogy

### CODE REVIEW

**Comment by tknorris** [comment]
Thanks for the PR! Did you check if the generic resolver would work for goflicker and speedwatch? You can see how to use it here: https://github.com/tknorris/script.module.urlresolver/blob/master/lib/urlresolver/plugins/estream.py

Also, can you fix the class name for TVLogy?

**Comment by Gujal00** [comment]
Thanks for that example.
Generic resolver is working for speedwatch, so updated
Also corrected class name for TVLogy

**Comment by tknorris** [comment]
Awesome. Should I go ahead and merge this PR or do you have more changes to make?

**Comment by Gujal00** [comment]
Please go ahead and merge. This PR is complete for now

**Pull request merged**
