### PR TITLE
Add media resolver for h265.se

### PR DESCRIPTION
**Pull request by dumbo0001**

### CODE REVIEW

**Comment by jsergio123** [comment]
can this use the GenericResolver?

**Comment by dumbo0001** [comment]
I didn't know when to use the GenericResolver. I took a quick look again in the GenericResolver. You're probably right. I will make the necessary changes and retest it.

**Comment by dumbo0001** [comment]
PR changed. It's now using the GenericResolver as base and implementing the necessary methods.

**Comment by jsergio123** [comment]
I have created it for you(see the pr below). Please close your pull request. Thank you.

https://github.com/tknorris/script.module.urlresolver/pull/368

**Comment by dumbo0001** [comment]
Thanks. 
Strange way of recreating a PR before it gets merged. 

PR closed.

**Pull request closed without merging**
