### PR TITLE
fixed pattern + fill up body with useful code

### PR DESCRIPTION
**Pull request by suuhm**
- pattern now usable with http://www.hostname and http://hostname links
- set up get_media_url and get_url methods inclusive useful urllib request in some cases

### CODE REVIEW

**Comment by tknorris** [comment]
Are you sure the old code wasn't working? The new GenericResolver does pretty much the same thing you did.

**Comment by tknorris** [comment]
Also, if you are going to write the resolver yourself, rather than re-use GenericResolver, then you need to inherit from Resolver instead of GenericResolver

**Comment by tknorris** [comment]
I just tested the current resolver and it worked fine for me. What problem were you trying to solve by changing it?

**Comment by suuhm** [comment]
hi, my probleme is this here: in the log: `02:27:56 14965.911133 T:2640311216   ERROR: URLResolver: HTTPError Error - From: ani-stream Link: http://ani-stream.com/embed-2emejeoimoad.html: HTTP Error 404: Not Found`

when i tried to resolve this link above from a website. have no success with this line: `from __generic_resolver__ import GenericResolver
`

**Comment by tknorris** [comment]
OK, we just need to update the domain and host then and it shoudl work. I'll make a commit and you can see my fix. give me a few mins

**Comment by tknorris** [comment]
committed. thanks for letting me know about the problem! I hope to see PRs from you in the future.

**Pull request closed without merging**
