### PR TITLE
update flashX #2

### PR DESCRIPTION
**Pull request by Viper2k4**
it took not even an hour ^^

### CODE REVIEW

**Comment by tknorris** [comment]
It seems like they'd prefer /pair to this but I'm not sure my message went to the people in question. I may add a comment to the source since they seem to be monitoring that.

**Comment by Viper2k4** [comment]
Yes a comment would be fine. I think here:

https://github.com/tknorris/script.module.urlresolver/blob/master/lib/urlresolver/plugins/flashx.py#L51

is the beste place. Because they mostly only mixup the regexes above.

**Comment by tknorris** [comment]
I added the comment. If they don't respond now, we can make flashx dynamically updateable.

**Comment by Viper2k4** [comment]
Add ur comment to my new PR :)

**Pull request merged**
