### PR TITLE
added support for cda.pl and trt.pl sources

### PR DESCRIPTION
**Pull request by homik**

### CODE REVIEW

**Comment by Viper2k4** [comment]
U should remove the debug prints and the comment stuff

**Comment by homik** [comment]
prints and comments removed.

**Comment by tknorris** [comment]
Thanks alot for the PR. Before I accept it, can you update the lines that append the headers to the stream url to use helpers.append_helpers instead of doing it manually? An example of it's use is here: https://github.com/tknorris/script.module.urlresolver/blob/master/lib/urlresolver/plugins/mailru.py#L50

**Comment by homik** [comment]
thanks for the hint. I fixed the urls.

**Pull request merged**
